version: "2"
services:
  app:
    container_name: api
    image: nilsemil/api:v12
    restart: always
    environment:
      - DATABASE_URL=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
      - JWT_KEY=myPrivateKey
    ports:
      - "8080:4000"
  mongo:
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    image: mongo
    ports:
      - "27017:27017"